Learnava.web/Areas/Admin/Controllers/UserController.cs
using Learnava.DataAccess;
using Learnava.DataAccess.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace Learnava.web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles =$"{SD.Role_Admin}")]
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
    
        public UserController(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;

        }

        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> LockUnLock([FromBody] string? id)
        {
            if(id is null)
            {
                return Json(new { success = true, message = "Error While Locking / UnLocking" });
            }
            var userFromDb = await _userManager.FindByIdAsync(id);

            if (userFromDb == null)
            {
                return Json(new { success = true, message = "Error While Locking / UnLocking" });

            }

            if (userFromDb.LockoutEnd != null && userFromDb.LockoutEnd > DateTime.Now)
            {
                userFromDb.LockoutEnd = DateTime.Now;
               await _userManager.UpdateAsync(userFromDb);
                TempData["Success"] = "User is un locked successfully";
            }
            else
            {
                if(userFromDb.Role == SD.Role_Admin)
                {
                    return Json(new { success = true, message = "Error While Locking / UnLocking Admin Users Can't be Locked" });
                }
                userFromDb.LockoutEnd = DateTime.Now.AddYears(1);
                await _userManager.UpdateAsync(userFromDb);
                TempData["Success"] = "User is locked for 1 year successfully";

            }
            return Json(new { success = true, message = "Delete Success" });
        }

        #region API Calls
        [HttpGet]
        public IActionResult GetAll()
        {

            var userList = _userManager.Users.Select(u => new
            {
                u.Id,
                u.Email,
                u.FullName,
                u.PhoneNumber,
                role = u.Role.Remove(0, 5),
                u.LockoutEnd
            });

            return Json(new { data = userList });
        }

        #endregion
    }
}

Learnava.web/Areas/Instructor/Controllers/CourseController.cs
using Learnava.BusinessLogic.IServiceContracts;
using Learnava.DataAccess;
using Learnava.DataAccess.Data.Entities;
using Learnava.web.VMModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Update;

namespace Learnava.web.Areas.Instructor.Controllers
{
    [Area("Instructor")]
    [Route("[area]/[controller]/[action]")]
    [Authorize(Roles =$"{SD.Role_Admin},{SD.Role_Instructor}")]
    public class CourseController : Controller
    {
        private readonly ICourseService _courseService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly UserManager<ApplicationUser> _userManager;

        public CourseController(ICourseService courseService, IWebHostEnvironment webHostEnvironment, UserManager<ApplicationUser> userManager)
        {
            _courseService = courseService;
            _webHostEnvironment = webHostEnvironment;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value!;
            ApplicationUser? user = await _userManager.FindByIdAsync(userId);
            ViewData["instructorName"] = user?.FullName;
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> UpSert(int? courseId)
        {
            var course = await _courseService.GetCourseByIdAsync(courseId);
            string userId = User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value!;
            ApplicationUser? user = await _userManager.FindByIdAsync(userId);
            ViewData["instructorName"] = user?.FullName;

            if (course == null)
                course = new()
                {
                    CreatedAt = DateTime.UtcNow,
                    InstructorId = userId,
                    
                };
            else
            {

                if (userId != course.InstructorId && !User.IsInRole(SD.Role_Admin))
                {
                    return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
                };

            }

            return View(course);
        }


        [HttpPost]
        public async Task<IActionResult> Upsert(Course course,IFormFile? file)
        {
            if(!ModelState.IsValid)
            {

                return View(course);
            }

            //New Course
            if(course.Id == 0)
            {
                var courseAfterAdding = await _courseService.AddCourseAsync(course);
            }

            string wwwRootPath = _webHostEnvironment.WebRootPath;
            string coursePath = @"Images/Courses/Course-" + course.Id;
            string finalPath = Path.Combine(wwwRootPath, coursePath);

            Directory.CreateDirectory(finalPath);

            if (file is not null)
            {
                string extension = Path.GetExtension(file.FileName).ToLower();
                string fileName = Guid.NewGuid().ToString() + extension;
                string filePath = Path.Combine(finalPath, fileName);

                using var fileStream = new FileStream(filePath, FileMode.Create);
                await file.CopyToAsync(fileStream);

                course.ImgUrl = Path.Combine("/Images/Courses/Course-" + course.Id, fileName).Replace("\\", "/");
                await _courseService.UpdateCourseAsync(course);
            }


            return RedirectToAction(nameof(Index));

        }


        [HttpDelete]
        public async Task<IActionResult> Delete(int courseId)
        {
            var course = await _courseService.GetCourseByIdAsync(courseId);

            if (course is null)
            {
                return NotFound();
            }
            string userId = User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value!;
            

            if ( course.InstructorId != userId && !User.IsInRole(SD.Role_Admin))
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }
            bool isDeleted = await _courseService.DeleteCourseAsync(courseId);

            return Json(new { success = (isDeleted is true)?  true : false,  message = (isDeleted is true) ? "Delete Success" : "Deleted Fail" });
        }

        #region Api Calls
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            string userId = User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value!;

            var user = await _userManager.FindByIdAsync(userId);

            IEnumerable<Course> courses;

            if (User.IsInRole(SD.Role_Admin))
            {
                courses = await _courseService.GetCoursesAsync(included:"Instructor");
            }
            else
            {
                courses = await _courseService.GetCoursesAsync(c => c.InstructorId == userId);
            }

            var result = courses.Select(c => new
            {
                c.Id,
                c.Title,
                c.Description,
                c.CreatedAt,
                instructorName = (c.Instructor is null) ? user!.FullName : c.Instructor.FullName,
                instructorEmail = (c.Instructor is null) ? user!.Email : c.Instructor.Email,
            });


            return Json(new { data = result });
        }
        #endregion
    }
}

Learnava.web/Areas/Student/Controllers/EnrollmentController.cs
using Microsoft.AspNetCore.Mvc;
using Learnava.BusinessLogic.IServiceContracts;
using Learnava.DataAccess;
using Learnava.DataAccess.Data.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;


namespace Learnava.web.Areas.Student.Controllers
{

    [Area("Student")]
    [Authorize]
    public class EnrollmentController : Controller
    {
        private readonly IEnrollmentService _enrollmentService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IStudentService _studentService;
        private readonly ICourseService _courseService;

        public EnrollmentController(IEnrollmentService enrollmentService, UserManager<ApplicationUser> userManager
            ,IStudentService studentService, ICourseService courseService)
        {
            _enrollmentService = enrollmentService;
            _userManager = userManager;
            _studentService = studentService;
            _courseService = courseService;
        }

        [Authorize(Roles = $"{SD.Role_Admin}, {SD.Role_Student}")]
        public IActionResult Index()
        {
            return View();
        }


        [Authorize(Roles =$"{SD.Role_Student}")]

        [HttpPost]
        public async Task<IActionResult> Create(int courseId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var student = await _studentService.GetStudentAsync(s => s.ApplicationUserId == userId);

            if(student == null)
            {
                return NoContent();
            }

            var alreadyEnrolled = await _enrollmentService.IsUserEnrolledAsync(courseId, student.Id);
            if (alreadyEnrolled)
            {
                TempData["Error"] = "You are already enrolled in this course.";
                return RedirectToAction(nameof(Index));
            }

            var enrollment = new Enrollment
            {
                CourseId = courseId,
                StudentId = student.Id,
                EnrollDate = DateTime.UtcNow
            };

            await _enrollmentService.CreateAsync(enrollment);

            return RedirectToAction(nameof(Index));

        }

        [HttpGet]
        public async Task<IActionResult> CourseContent(int courseId)
        {
            var course = await _courseService.GetCourseByIdAsync(courseId,included: "Videos");

            if(course is null)
            {
                return NoContent();
            }
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var student = await _studentService.GetStudentAsync(s => s.ApplicationUserId == userId);

            if (student is null)
            {
                if (!User.IsInRole(SD.Role_Admin) && course.InstructorId != userId)
                {
                    return NotFound();
                }
                return View(course);
            }
            var enroll = await _enrollmentService.IsUserEnrolledAsync(courseId, student.Id);

            if(!enroll)
            {
                return NotFound();
            }
            return View(course);
        }



        #region Api calls
        [Authorize(Roles = $"{SD.Role_Admin}, {SD.Role_Student}")]
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            IEnumerable<Enrollment> enrollments;
            string userId = User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value!;

            if (User.IsInRole(SD.Role_Admin))
            {
                enrollments = await _enrollmentService.GetEnrollmentsAsync(included: "Student,Course");
            }
            else
            {
                enrollments = await _enrollmentService
                    .GetEnrollmentsAsync(e => e.Student!.ApplicationUserId == userId, included: "Student,Course");
            }
            var result = new List<object>();
            foreach (var e in enrollments)
            {
                var instructor = await _userManager.FindByIdAsync(e.Course!.InstructorId);
                var student = await _userManager.FindByIdAsync(e.Student!.ApplicationUserId);

                result.Add(new
                {
                    instructorName = instructor?.FullName,
                    instructorEmail = instructor?.Email,
                    studentName = student?.FullName,
                    studentEmail = student?.Email,
                    e.Id,
                    e.CourseId,
                    e.EnrollDate,
                    courseTitle = e.Course.Title
                });
            }


            return Json(new { data = result });

        }

        [HttpDelete]
        [Authorize(Roles = $"{SD.Role_Admin},{SD.Role_Student}")]  
        public async Task<IActionResult> Delete(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var enrollment = await _enrollmentService.GetEnrollmentAsync(e => e.Id == id, included: "Student");

            if(enrollment is null)
            {
                return NotFound();
            }

            if(enrollment.Student!.ApplicationUserId != userId && !User.IsInRole(SD.Role_Admin))
            {
                return BadRequest();
            }
            var isDeleted = await _enrollmentService.DeleteEnrollmentAsync(id);
            return Json(new { success = (isDeleted is true) ? true : false, message = (isDeleted is true) ? "Delete Success" : "Deleted Fail" });

        }
        #endregion

    }
}

Learnava.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Learnava.web</title>

    <!-- Bootstrap & Learnava CSS -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Learnava.web.styles.css" asp-append-version="true" />

    <!-- Icons & External Styles -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="Customer" asp-controller="Home" asp-action="Index">Learnava Academy</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (User.IsInRole(SD.Role_Instructor) || User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="bi bi-folder"></i> Content Management
                                </a>
                                <ul class="dropdown-menu shadow">
                                    @if (User.IsInRole(SD.Role_Admin))
                                    {
                                        <li>
                                            <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">
                                                <i class="bi bi-person"></i>Manage Users
                                            </a>
                                        </li>
                                    }
                                    <li>
                                        <a class="dropdown-item" asp-area="Instructor" asp-controller="Course" asp-action="Index">
                                            <i class="bi bi-journal-text"></i>Manage Courses
                                        </a>
                                    </li>
                                    
                                </ul>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_Student) || User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="Student" asp-controller="Enrollment" asp-action="Index">
                                    <i class="bi bi-people-fill"></i> Enrollments
                                </a>
                            </li>
                        }


                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="bi bi-envelope"></i> Contact Us
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end shadow">
                                <li>
                                    <a class="dropdown-item" href="https://wa.me/201080850238" target="_blank">
                                        <i class="bi bi-whatsapp text-success"></i> WhatsApp
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="mailto:3laaelmasry2005a@gmail.com">
                                        <i class="bi bi-envelope-at text-primary"></i> Gmail
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="https://www.linkedin.com/in/3laa-elmasry-9265b4241" target="_blank">
                                        <i class="bi bi-linkedin text-info"></i> LinkedIn
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="https://github.com/3laaElmasry" target="_blank">
                                        <i class="bi bi-github text-secondary"></i> GitHub
                                    </a>
                                </li>
                            </ul>

                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container mb-3 pb-3" style="min-height:100vh">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="text-center">
            Learnava Academy Made <i class="bi bi-heart-fill text-danger"></i> by Elmasry
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/2.2.2/js/dataTables.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/gk6bhxkfhg9ypybreeknnb9ahcsmsn9xw21h2sriwasw6xjm/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <partial name="_Notification" />
</body>
</html>

Learnava.web/Views/Shared/_Notification.cshtml
@* Views/Shared/_Notification.cshtml *@
@{
    var success = TempData["success"] as string;
    var error = TempData["error"] as string;
    var warning = TempData["warning"] as string;
    var info = TempData["info"] as string;
}

@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script>
        $(document).ready(function () {
        @if (!string.IsNullOrEmpty(success))
        {
            <text>toastr.success("@success");</text>
        }
        @if (!string.IsNullOrEmpty(error))
        {
            <text>toastr.error("@error");</text>
        }
        @if (!string.IsNullOrEmpty(warning))
        {
            <text>toastr.warning("@warning");</text>
        }
        @if (!string.IsNullOrEmpty(info))
        {
            <text>toastr.info("@info");</text>
        }
        });
    </script>
}